### ISSUE TITLE
Melhorar Actions

### ISSUE THREAD

**Issue by silv4b** [silv4b/silv4b-dark-theme#2]
Tentar de alguma forma diminuir a quantidade de código duplicado no arquivo de deploy [deploy.yml](https://github.com/silv4b/silv4b-dark-theme/blob/main/.github/workflows/deploy.yml).

Código duplicado:

``` yml
runs-on: ubuntu-latest
  steps:
    - run: git config --global user.email "brunosilv_a@outlook.com"
    - run: git config --global user.name "Bruno Silva"
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
      name: 📩 Update npm
    - run: npm install -g npm  # Adding a cmd to update the npm version of the server
      name: 📦 Installing vsce package
    - run: npm install -g vsce@1.96.1 --save-dev
      name: ✅ Publishing on marketplace
```

**Comment by silv4b** [comment]
Aprimorado! 

Novo código:

```yml
name: 📦 Deploy

on:
  push:
    branches:
      - main
  
jobs:
  build-base:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        semantic: [major, minor, patch]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'  
      - uses: haya14busa/action-cond@v1
        id: condval
        with:
          cond: ${{ startsWith(github.event.head_commit.message, matrix.semantic) }}
          if_true: 'true'
          if_false: 'false'
      - name: 📦 Verify scope
        run: echo "${{ github.event.head_commit.message }}"
      - name: 📦 Installing vsce package
        run: npm install -g vsce@1.96.1 --save-dev
      - name: ✅ Publishing on Marketplace
        if: | 
          steps.condval.outputs.value == 'true'
        run: |
          vsce publish ${{ matrix.semantic }} -p ${{ secrets.AZURE_SECRET }}
```
